Tencent/tdesign-vue-next-starter

- src/layouts/components/Header.vue
- src/pages/dashboard/base/index.vue
- src/pages/dashboard/detail/index.vue
- src/pages/form/base/constants.ts
- src/pages/form/base/index.less
- src/pages/form/base/index.vue
- src/pages/list/base/index.vue
- src/pages/list/card/index.vue
- src/pages/list/components/CommonTable.vue
- src/pages/result/success/index.vue
- src/pages/user/index.vue
> fix(responsive): responsive ui edit

- src/App.vue
- src/layouts/setting.vue
- src/store/modules/setting.ts
> fix: copy custom config

- package.json
- pnpm-lock.yaml
fix https://github.com/Tencent/tdesign-vue-next-starter/issues/43
> fix(package.json): tdesign-icons-vue-next

- package.json
- src/pages/form/base/index.vue
fix form base page validate error
> fix(form/base): fix form base validate

- src/layouts/components/MenuContent.tsx
> feat(router): add route hidden

- src/style/layout.less
https://github.com/Tencent/tdesign-vue-next/issues/253
https://github.com/Tencent/tdesign-vue-next/issues/283
before
after
- fix(tabel): 修复表格 `fixed` 单元格层级过高，与 `menu` 弹窗显示冲突
> fix(sidenav): fix sideNav z-index

- package.json
- src/App.vue
- src/components/color/index.vue
- src/config/color.ts
- src/interface.ts
- src/layouts/components/Header.vue
- src/layouts/components/Notice.vue
- src/layouts/components/Search.vue
- src/layouts/components/SideNav.tsx
- src/layouts/index.tsx
- src/layouts/setting.vue
- src/main.ts
- src/pages/dashboard/base/index.ts
- src/pages/dashboard/base/index.vue
- src/pages/dashboard/detail/index.vue
- src/pages/detail/deploy/index.vue
- src/pages/detail/secondary/index.vue
- src/pages/login/components/Header.vue
- src/pages/login/components/Login.vue
- src/pages/user/index.vue
- src/permission.ts
- src/router/index.ts
- src/store/index.ts
- src/store/modules/notification.ts
- src/store/modules/permission.ts
- src/store/modules/setting.ts
- src/store/modules/user.ts
#51 
- refactor(组件名称):  使用pinia 替换vuex，重构状态管理相关逻辑
- fix: 修复头部搜索框的样式问题
- tdesign-vue-next 升级到 0.9.2
> refactor(pinia): use pinia refactor store

- package.json
- src/layouts/components/SideNav.tsx
- src/layouts/setting.vue
- src/pages/form/step/index.vue
> fix(setting): fix setting page

- src/layouts/components/MenuContent.tsx
- 新特性提交，支持菜单配置跳转外链
```
{
path: 'https://tdesign.tencent.com',
meta: { title: '友情链接' },
},
```
- feat: 支持菜单配置跳转外链
> feat: 路由支持配置跳转外链

- package.json
> add dev:linux command

- src/store/modules/user.ts
> update mock roles

- src/store/modules/setting.ts
- 日常 bug 修复 修复图表文字颜色异常问题
- fix: 修复图表文字颜色异常问题
> fix: 修复图表文字颜色异常

- .npmrc
- [CI/CD 改进
-  [使用pnpm打包报错](https://github.com/Tencent/tdesign-vue-next-starter/issues/43)
- 对pnpm包管理器的支持
- feat: 支持pnpm包管理器
> feat(support-pnpm): add to. Npmrc file to solve the problem of pnpm dependency

- package.json
- 日常 bug 修复 增加了ci test:coverage 先增加个script避免其他人PR fail
> fix: ci test:coverage

- src/layouts/components/Search.vue
修复issue#126中的搜索框样式异常
修复[issue #126](https://github.com/Tencent/tdesign-vue-next-starter/issues/126)中提到的搜索框样式异常问题；
* 修复前：
* 修复后：
- fix(Search): 样式异常
> 修复issue#126

- .eslintrc
- package.json
- src/App.vue
- src/layouts/blank.vue
- src/layouts/components/Header.vue
- src/layouts/components/Notice.vue
- src/layouts/components/Search.vue
- src/layouts/setting.vue
- src/pages/list/components/CommonTable.vue
- src/pages/login/components/Login.vue
- src/pages/login/components/Register.vue
- src/pages/login/index.less
- src/pages/login/index.vue
修复 #135 
- fix(style): 修复style缺少scoped的问题，新增对应的lint校验
> feat: add lint for scoped-css

- src/assets/assets-result-maintenance.svg
- src/components/result/index.vue
- src/pages/result/maintenance/index.vue
- src/router/modules/components.ts
- 新特性提交 新增维护中页面
- #128 
- feat: 新增维护页
> chore: add maintanance page

- src/layouts/index.tsx
修复 #151
#151 
不同的路由的content-key应该不一致
> fix: 多个滚动列表之间切换时，页面不刷新导致的样式BUG

- package.json
- src/pages/form/base/index.vue
- src/pages/list/base/index.vue
- src/pages/list/components/CommonTable.vue
- feat(tdesign): 升级 `tdesign-vue-next` 到 `0.15.1`
> feat: upgrade to 0.15.1

- src/layouts/index.tsx
- src/store/modules/tabs-router.ts
- 日常 bug 修复
- 新特性提交
- 演示代码改进
- fix: 处理设置layout key导致缓存失效的问题
- feat: 新增不需要缓存路由的代码示例
> feat: ignore cache demo

- src/interface.ts
- src/store/modules/tabs-router.ts
- 日常 bug 修复
- fix: 修复多标签tab页的逻辑问题
> fix: tab route close logic

- src/layouts/index.tsx
修复 #151
#151 
页面更新时将content容器滚动条重置至顶部
> 修复页面滚动条不重置的问题

- package.json
- 日常 bug 修复 升级TDesign 修复菜单样式部分缺陷
-  https://github.com/Tencent/tdesign-vue-next/issues/882
- feat: 升级组件库依赖至0.15.4
- fix: 修复菜单样式在暗黑模式下的箭头、颜色问题
> feat: upgrade tdesign

- package.json
- src/pages/nest-menu/Index.vue
- src/router/index.ts
- src/router/modules/others.ts
> chore: add 3rd layer menu demo

- src/pages/user/constants.ts
> chore: fix incorrect content

- src/layouts/index.tsx
> fixed issue 172

- package.json
- src/pages/dashboard/base/components/middle-chart.vue
- src/pages/dashboard/base/components/overview.vue
- src/pages/dashboard/detail/index.vue
- src/pages/detail/deploy/index.vue
- src/pages/list/components/CommonTable.vue
- src/pages/user/index.vue
- src/style/index.less
- src/style/layout.less
> feat: upgrade 0.16.0

- src/layouts/setting.vue
- src/style/layout.less
> fix: setting radio height

- src/utils/request/index.ts
> fix: demo use normal request

- src/style/index.less
> fix: 修复reset和A标签样式缺失导致的问题

- src/layouts/setting.vue
> fix: remove height and width settings of .setting-layout-color-group

- src/layouts/components/Breadcrumb.vue
> fix: 修复面包屑获取路由参数报错的问题

- package.json
- src/style/layout.less
- feat(Verision): 升级`tdesign-vue-next` 到 `0.17.3`
> feat: upgrade 0.17.3

- package.json
> chore: 修改发版时没修改的版号

- src/layouts/components/Breadcrumb.vue
在参数路由场景下，原本的Breadcrumb是会显示参数当成Breadcrumb标题，现在添加了hiddenBreadcrumb如果路由不想在Breadcrumb显示则可以在meta中写上`hiddenBreadcrumb: true`即可隐藏
现在增加了判断是否遍历到了参数，如果当前遍历的是参数则隐藏
- feat: 添加 `hiddenBreadcrumb` 选项
> feat: 添加hiddenBreadcrumb选项

- src/api/detail.ts
- src/api/list.ts
- src/api/model/detailModel.ts
- src/api/model/listModel.ts
- src/pages/detail/advanced/index.vue
- src/pages/detail/deploy/index.vue
- src/pages/list/base/index.vue
- src/pages/list/card/index.vue
- src/pages/list/components/CommonTable.vue
- src/types/axios.d.ts
- src/types/interface.d.ts
- src/utils/request/index.ts
> feat: 将请求分类至api文件夹

- src/pages/dashboard/base/index.ts
- src/pages/dashboard/detail/index.ts
- src/pages/detail/deploy/index.ts
- src/pages/user/index.ts
- fix(Echart): 修复图表的 `warn` 问题
> fix(echart): 修复图表的warn问题

- src/layouts/components/MenuContent.tsx
- src/router/index.ts
- src/types/globals.d.ts
- tsconfig.json
- feat: router修改为自动导入
- feat: 添加orderNo令自动导入的路由可以排序
> feat: router修改为自动导入

- package.json
- src/layouts/components/Notice.vue
before
after
- feat: 升级 `0.17.4` 版本
- fix(Header): 修复 `notice icon` 位置偏移
> feat: upgrade 0.17.4

- src/constants/index.ts
- src/pages/list/base/index.vue
- src/pages/list/components/CommonTable.vue
`receipt`拼写错误
- fix(constants): `RECEIPT`拼写错误
> fix(typo): `RECEIPT`拼写错误

- package.json
> feat: upgrade 0.18.0

- package.json
> feat: upgrade 0.18.1

- src/layouts/components/SideNav.tsx
- src/router/index.ts
> feat: 新增配置支持子菜单是否默认展开

- src/layouts/components/Content.vue
> feat: 添加组件key

- package.json
> feat: upgrade 0.19.0

- src/pages/dashboard/base/components/MiddleChart.vue
- src/pages/dashboard/detail/index.vue
- #239 
- fix: 修复改变颜色/模式 出现页面卡死等异常的问题
> fix: 修复改变颜色/模式 出现页面卡死等异常的问题

- src/pages/dashboard/base/components/MiddleChart.vue
> fix: 修复侧边栏开合时图表没有刷新

- src/pages/login/components/Login.vue
> fix: 填补登录页面缺失的手机号输入框及相关逻辑

- package.json
- src/router/index.ts
⚠️**注意本PR不兼容以往的路由代码，需要记得修改不然编译必炸**⚠️
- feat: 升级vue-router版本
> feat: 升级vue-router版本

- src/router/modules/others.ts
- #260 
- fix: 修复更新vue-router版本后的遗留问题
> fix: 修复更新vue-router版本后的遗留问题

- package.json
- src/router/index.ts
- src/router/modules/others.ts
> fix: revert vue-router upgrade

- src/layouts/components/Content.vue
- https://github.com/Tencent/tdesign-vue-next-starter/issues/264
- fix: 处理增加key配置导致的login页的异常问题
> fix: login reload crush

- src/types/interface.d.ts
> chore: 补充类型声明

- src/utils/request/index.ts
- fix: 修正发起请求时formData类型的数据会被错误过滤的问题
> fix: 修正发起请求时formData类型的数据会被错误过滤的问题

- src/permission.ts
- fix: 修正如果在使用了 userStore 内的数据的页面进行退出登录操作时会因为相关数据提前清除而报错的问题
> fix: 修正如果在使用了 userStore 内的数据的页面进行退出登录操作时会因为相关数据提前清除而报错的问题

- package.json
> feat: upgrade 0.20.2

- src/router/modules/others.ts
> feat: loginRedirect add redirect

- src/layouts/index.tsx
- https://github.com/Tencent/tdesign-vue-next-starter/issues/288
- fix: 修复多标签页刷新功能失效的问题
> fix: tab-router refresh fail

- src/layouts/index.vue
> fix: miss layout header

- package.json
- src/layouts/index.vue
> Chore/release 0.5.0

- src/layouts/components/Content.vue
fix: 示例增加 suspense 代码解决打开多个标签后退出会报错的问题
> fix: 解决当打开多个标签后 退出会报错的问题

-  README-en_US.md
- Translate documentation and provide English version docs
> fix: typo and grammar

- src/pages/dashboard/base/index.vue
- src/style/layout.less
|修改前|修改后|
|  ----  | ----  |
|![image](https://user-images.githubusercontent.com/487040/188853788-19ec558a-4a6d-487f-b4d3-6cccacc22869.png)|![image](https://user-images.githubusercontent.com/487040/188853922-bd1427e0-ded7-4fb9-8687-6b7e43de3b82.png)|
- fix(footer): 修复底部版权信息垂直居中问题
> fix(footer): 修复底部版权信息垂直居中问题

- src/layouts/components/Breadcrumb.vue
https://github.com/Tencent/tdesign-vue-next-starter/issues/240
|修改前|修改后|
|  ----  | ----  |
|![image](https://user-images.githubusercontent.com/487040/188821462-4ea68d40-0b36-436c-b34d-c90aa05055d7.png)|![image](https://user-images.githubusercontent.com/487040/188821648-b5403c9d-8f24-408c-a40a-90db2ff4ef14.png)|
- fix(breadcrumb): 修复面包屑导航垂直居中问题
> fix(breadcrumb): 修复面包屑导航垂直居中问题

- package.json
- src/App.vue
- src/layouts/index.vue
- src/layouts/setting.vue
- src/permission.ts
- src/store/index.ts
- src/store/modules/notification.ts
- src/store/modules/setting.ts
- src/store/modules/tabs-router.ts
- src/store/modules/user.ts
#278 
- feat(持久化): 使用插件将store数据持久化（除 permission）([issue #278](https://github.com/Tencent/tdesign-vue-next-starter/issues/278))
> feat(持久化): 使用插件将store数据持久化（除 permission）

-  README-en_US.md
- README-zh_CN.md
- src/layouts/index.vue
- https://github.com/Tencent/tdesign-vue-next-starter/issues/296
- docs: add README in English by @paiakarit 
> docs: README in English

- src/layouts/components/LayoutContent.vue
[多标签页] 支持非当前打开的标签页右键操作: https://github.com/Tencent/tdesign-vue-next-starter/issues/277
- feat: [多标签页] 支持非当前打开的标签页右键操作: https://github.com/Tencent/tdesign-vue-next-starter/issues/277
> feat: multiple tabs support action

- src/layouts/components/LayoutSideNav.vue
- src/utils/request/index.ts
> fix: 修复sidenav参数错误

- src/store/modules/user.ts
- src/utils/request/index.ts
- #313 
- fix: 移除user的持久化修复其导致的问题
> fix: 移除user的持久化修复其导致的问题

- src/store/modules/user.ts
> fix: 修复持久化的问题

- src/layouts/components/MenuContent.vue
> fix: 修复路径重复拼接的问题

- package.json
- feat: 升级tdesign-vue-next至0.23.0 修复页面切换吸附效果没有重新计算的问题 ([issue#1207](https://github.com/Tencent/tdesign-vue-next/issues/1207))
> feat: upgrade tdesign to 0.23

- package.json
- https://github.com/Tencent/tdesign-vue-next-starter/issues/334
- fix: 修复dropdown重构引入的v-if渲染问题导致的渲染异常
> chore: fix dropdown refactor issue

- package.json
- fix: 升级TDesign，修复dropdown组件重构引发的部分样式丢失的问题
> chore: upgrade tdesign-vue-next to 0.24.2

- package.json
> chore: release 0.5.3

- package.json
- src/router/index.ts
- https://github.com/Tencent/tdesign-vue-next-starter/issues/267
- chore: 将vue-router和vue-tsc升级
> chore: 将vue-router和vue-tsc升级

- src/layouts/components/Header.vue
> fix: 修复事件绑定错误(#344)

- src/layouts/components/Header.vue
> fix: 导航布局side模式小屏显示问题

- package.json
- src/layouts/components/Header.vue
- src/pages/dashboard/base/index.ts
- src/pages/dashboard/base/index.vue
- src/pages/dashboard/detail/index.vue
- feat: 升级组件库依赖至0.24.7 新增尺寸相关Design Token 手动更新部分样式细节
> feat: upgrade tdesign-vue-next

- src/style/layout.less
Co-authored-by: tnt group <dodu@live.cn>
- fix: 修复头部样式的异常
> fix: header height

- src/style/layout.less
> fix: layout height

- src/layouts/components/Header.vue
- src/pages/login/components/Login.vue
- src/permission.ts
> feat: 优化登录跳转支持回跳带query参数的页面

- src/style/layout.less
修复分页错位问题
- fix(dateRangePicker): 修复DateRangePicker组件内分页样式显示异常
> fix(dateRangePicker): 修复DateRangePicker组件内分页样式显示异常

- src/components/product-card/index.vue
- src/layouts/components/Content.vue
- src/layouts/components/Header.vue
- src/layouts/components/LayoutContent.vue
- src/layouts/components/MenuContent.vue
- src/layouts/components/Notice.vue
- src/layouts/components/SideNav.vue
- src/layouts/setting.vue
- src/pages/detail/secondary/index.vue
- src/store/modules/notification.ts
- src/store/modules/tabs-router.ts
- feat: 类型引入声明type 支持通过starter CLI转换成JS项目
> feat: import type as type

- src/pages/login/components/Login.vue
> fix: complete form rule type

- src/hooks/event/useWindowSizeFn.ts
- src/layouts/components/Content.vue
- src/layouts/components/FrameBlank.vue
- src/layouts/components/FrameContent.vue
- src/layouts/components/MenuContent.vue
- src/layouts/frame/index.vue
- src/layouts/frame/useFrameKeepAlive.ts
- src/layouts/index.vue
- src/router/modules/iframe.ts
- src/types/interface.d.ts
> feat: 打开外部页面（内嵌/外链）

- package.json
- src/layouts/components/MenuContent.vue
- src/layouts/components/SideNav.vue
- src/pages/detail/advanced/constants.ts
- src/pages/detail/deploy/constants.ts
- src/pages/form/base/constants.ts
- src/pages/form/step/constants.ts
- src/pages/form/step/index.vue
- src/pages/list/base/constants.ts
- src/pages/list/base/index.vue
- src/pages/list/card/components/DialogForm.vue
- src/pages/list/components/CommonTable.vue
- src/pages/login/components/Register.vue
- src/store/modules/setting.ts
- tsconfig.json
> feat: add tdesign components typing tips

- package.json
> chore: release 0.6.1

- .env.site
- package.json
- src/config/proxy.ts
- src/router/index.ts
- fix: 新增site mode 不影响正常用户使用 修复官网特定CDN回源策略导致站点部署资源访问异常的问题
- feat: 默认改为history路由模式
> fix: site path and use history router

- src/utils/request/Axios.ts
> fix: remove axios ignoreRepeatRequest config

- .env
- .env.development
- .env.site
- src/layouts/components/Header.vue
- src/pages/detail/advanced/index.vue
- fix: 修复版本升级引入的类型问题
- fix: 修复部署环境默认静态资源请求路径错误的问题
> chore: fix surge deploy

- package.json
- stylelint.config.js
> fix: stylelint 14 error

- src/layouts/components/Header.vue
- src/layouts/components/Notice.vue
- src/layouts/components/Search.vue
- src/layouts/setting.vue
- src/pages/dashboard/base/components/MiddleChart.vue
- src/pages/dashboard/base/components/OutputOverview.vue
- src/pages/dashboard/base/components/RankList.vue
- src/pages/dashboard/base/components/TopPanel.vue
- src/pages/dashboard/base/constants.ts
- src/pages/dashboard/base/index.vue
- src/pages/dashboard/detail/index.vue
- src/style/layout.less
- fix: dashboard&layout style bug
> fix: dashboard&layout style bug

- package.json
- src/layouts/components/MenuContent.vue
> fix: 修复菜单图标样式问题

- src/layouts/components/MenuContent.vue
> perf: 优化菜单生成

- src/layouts/components/Notice.vue
- src/pages/login/components/Header.vue
- src/pages/login/components/Login.vue
- src/pages/login/index.less
- src/store/modules/notification.ts
- src/style/layout.less
- fix: layout/notice/login style bug
> fix: layout/notice/login style bug

- src/pages/list/tree/index.vue
https://github.com/Tencent/tdesign-vue-next/issues/2405
- fix:demo list tree filter
> fix: 拼音输入的问题

- package.json
- src/layouts/setting.vue
> fix: setting default style

- package.json
> chore: release 0.7.2

- stylelint.config.js
https://github.com/Tencent/tdesign-vue-next-starter/issues/435
- [√] 本条 PR 不需要纳入 Changelog
- [√] 文档已补充或无须补充
- [√] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√] Changelog 已提供或无须提供
> fix: stylelint

- .vscode/settings.json
- src/router/index.ts
> fix: globEager deprecated

- package.json
> chore: release 0.7.3

- package.json
- fix: 修正 @types/nprogress 错误安装在了 dependencies 的问题
- fix: 去除无用的 @types/ws 包
> fix: move @types/nprogress from dependencies to devDependencies

- src/utils/request/Axios.ts
- src/utils/request/AxiosTransform.ts
- src/utils/request/index.ts
> fix: 修正请求出错重试后触发两次回调的问题

- src/layouts/components/MenuContent.vue
https://github.com/Tencent/tdesign-vue-next/issues/2629
- fix: 修复多级菜单高亮问题
> fix: 修复多级菜单高亮问题

- package.json
> chore: revert echarts to fix render intersection

- mock/index.ts
- src/api/model/permissionModel.ts
- src/layouts/components/Content.vue
- https://github.com/Tencent/tdesign-vue-next-starter/issues/469
docs change https://github.com/TDesignOteam/tdesign-starter-docs/pull/21
- feat: meta新增`keep-alive` 配置
> feat: support keep-alive meta config

- package.json
> chore: release 0.7.4

- src/main.ts
- src/pages/dashboard/detail/index.vue
- src/style/layout.less
> chore: card detail style

- src/pages/dashboard/base/components/OutputOverview.vue
- src/pages/dashboard/base/components/TopPanel.vue
- src/pages/dashboard/detail/index.vue
- src/pages/detail/advanced/components/Product.vue
- src/pages/detail/advanced/index.less
- fix: update token for TCloud-Theme
> fix: update token

- src/permission.ts
> 先验证token，再获取菜单

- src/layouts/components/Header.vue
- src/store/modules/user.ts
修改前：固定为`Tencent`
修改后：动态根据实际用户名展示
> 优化展示用户名，而不是固定为Tencent

- src/permission.ts
> perf: 路由守卫获取菜单异常，跳转登录页并弹窗提示

- package.json
> chore: release 0.7.5

- .gitattributes
- .vscode/settings.json
- package.json
- src/pages/detail/secondary/index.vue
- src/permission.ts
- src/store/modules/user.ts
- src/utils/request/index.ts
- chore: sync develop branch to site branch 
> chore: sync develop branch to site branch

- package.json
https://github.com/okonet/lint-staged#v10
- chore: lint-staged v10以后不需要git add
> chore: lint-staged remove git add

- package.json
> feat: upgrade tdesign set

- package.json
> chore: release 0.7.6

- src/utils/request/index.ts
> fix: 请求204无内容直接返回判断

- src/utils/request/Axios.ts
> feat: axios支持格式化params

- src/layouts/setting/page-config.vue
- build CI fail for node version, fixed in https://github.com/Tencent/tdesign/pull/362
- fix: 站点样式问题修复
> fix(site): consistency of drawer style

- package.json
> chore: release 0.7.7

- src/layouts/components/Content.vue
fix: (https://github.com/Tencent/tdesign-vue-next-starter/issues/507)
> fix: 路由跳转表头闪烁

- package.json
- stylelint.config.js
closed #554
- feat: 移除Stylelint-less依赖
> feat: 移除Stylelint-less依赖

- package.json
- src/layouts/setting.vue
- src/style/index.less
- src/style/layout.less
- src/style/reset.less
- stylelint.config.js
> fix: stylelint  error

- src/pages/list/components/CommonTable.vue
> fix: list demo  status defalut object

- package.json
> chore: release 0.8.0

- src/style/layout.less
- stylelint.config.js
> feat(stylelint): number-leading-zero deprecated

- src/pages/dashboard/base/components/RankList.vue
- src/pages/detail/advanced/index.vue
- src/pages/detail/deploy/index.vue
- src/pages/list/base/index.vue
- src/pages/list/components/CommonTable.vue
- src/style/reset.less
- stylelint.config.js
https://github.com/Tencent/tdesign-vue-next-starter/issues/564
- fix: t-link hover color
> fix: t-link hover color

- package.json
> chore: update tdesign-icons-vue-next

- package.json
- src/pages/list/card/components/DialogForm.vue
- vite.config.ts
> fix: import/order

- src/pages/list/card/components/DialogForm.vue
- src/pages/list/card/index.vue
- src/style/index.less
- src/style/layout.less
- stylelint.config.js
> feat(stylelint): 移除没用的规则

- src/style/layout.less
> fix: fix button style effect

- src/pages/dashboard/base/components/MiddleChart.vue
- src/pages/detail/advanced/index.vue
- src/pages/detail/deploy/index.vue
可能因上游td组件调整，卡片组件的操作插槽名由option调整为actions，恢复显示原设计操作插槽
- fix: 修正部分模板页面卡片组件操作插槽用法
> fix: 修正部分模板页面卡片组件操作插槽用法

- src/layouts/components/MenuContent.vue
- fix: 修复升级 1.5.0 版本后menu 菜单需要 router 配置
> fix(menu): need router props

- src/router/index.ts
顶部菜单初始化高亮失效，组件的问题 https://github.com/Tencent/tdesign-vue-next/issues/3163
> revert: fix顶部菜单高亮

- src/layouts/components/Notice.vue
Before:
After:
- fix(notice): 优化”暂无通知“UI
> fix(notice): 优化”暂无通知“UI

- package.json
> feat:  node version >=16.0.0

- package.json
> chore: release 0.9.0

- src/hooks/index.ts
> fix: echarts resize error

- mock/index.ts
fix https://github.com/Tencent/tdesign-vue-next-starter/issues/629
- fix: mock环境获取菜单地址不匹配
> fix: mock menu

- src/locales/lang/zh_CN/pages/result.ts
> fix(i18n): 修复缺失的语言词条

- src/pages/user/index.vue
closed #633 
- fix(i18n): 修复用户中心词条不生效的问题
> fix(i18n): 修复用户中心词条不生效的问题

- .husky/commit-msg
- .husky/pre-commit
- .husky/prepare-commit-msg
> fix: 修复husky可能找不到npx命令的问题

- src/pages/user/constants.ts
- src/pages/user/index.vue
> fix(i18n): 修复用户中心词条不生效的问题 (#634)

- src/layouts/setting/page-config.vue
closed #572 
- fix(site): 修复示例无法复制配置的问题
> fix(site): 修复示例无法复制配置的问题

- src/pages/user/index.vue
> feat: use $t

- package.json
- src/pages/dashboard/base/components/TopPanel.vue
- src/utils/route/index.ts
> fix: 修复循环过深的问题

- package.json
> fix: hotfix useRoute bug after vue 3.4 release

- src/layouts/components/Content.vue
> chore: sync main to site

- package.json
- src/pages/list/base/index.vue
- src/router/index.ts
- tsconfig.json
- closed #679 
- feat: 升级至Vue3.4，修复Route调用方式造成的问题
> feat: upgrade to vue 3.4 and fix route issues

- package.json
- src/pages/detail/advanced/index.vue
- src/pages/detail/base/index.less
- src/pages/detail/base/index.vue
- src/pages/user/index.vue
- feat: 使用`t-descriptions` 替换详情页代码
> feat: replace detail page code with t-descriptions

- package.json
> revert: 回退Vue 3.3

- package.json
> revert: 回退Vue 3.3 (#709)

- .gitignore
- package-lock.json
- package.json
背景：原本没有保留某种lock的本意是让用户自行选择，但是实际执行下来发现有许多用户因为lock文件没有保留，导致出现本地和线上不一致的问题，所以恢复其中一种lock文件
- feat: 调整默认lock文件配置
> chore: remove npm lock file ignore

- README-zh_CN.md
- README.md
> fix: 修复README单词拼写错误

- package-lock.json
- package.json
- src/types/interface.d.ts
- https://github.com/Tencent/tdesign-vue-next-starter/issues/721
- https://github.com/Tencent/tdesign-vue-next-starter/issues/671
- fix: 修复升级至 vue3.4及3.5的生产模式下的问题
> fix: fix tabs page error in production after 3.4

- src/main.ts
> fix: 修复引入顺序导致异常

- src/layouts/components/Breadcrumb.vue
- closed https://github.com/Tencent/tdesign-vue-next-starter/issues/809
- fix(Breadcrumb): 修复面包屑状态异常
> fix: 修复面包屑状态异常

- src/layouts/components/Breadcrumb.vue
- closed https://github.com/Tencent/tdesign-vue-next-starter/issues/809
- fix(Breadcrumb): 修复面包屑状态异常
> fix(Breadcrumb): 修复面包屑状态异常

- package-lock.json
- src/layouts/components/Content.vue
- fix #845
- fix(frame): 修复内嵌网页不能正常显示的问题
> fix(frame): 修复内嵌网页不能正常显示的问题
