- src/pages/dashboard/base/index.ts
- src/pages/dashboard/base/index.vue
- src/pages/dashboard/detail/index.vue
- src/pages/detail/deploy/index.vue
- src/pages/user/index.vue
1. charts size should be 42
2. text color under dark mode
> fix(charts): rerender text color when change mode

- src/pages/list/components/CommonTable.vue
src/pages/list/components/CommonTable.vue中有两个t-input标签的class多写了个反引号（`）。
> feat(list): Remove the extra backquotes from class

- src/layouts/components/Notice.vue
修复通知中点击 "查看全部"，router为undefined导致的无法跳转问题。
> fix(notice): fix goDetail error

- src/layouts/components/Header.vue
修复issue#126中的顶部菜单栏未选中的样式问题
修复[issue #126](https://github.com/Tencent/tdesign-vue-next-starter/issues/126)中提到的顶部菜单栏未选中样式异常问题；
* 修复前：
* 修复后：
- fix(Header): 样式异常
> 修复issue#126

- src/layouts/components/Header.vue
- src/layouts/components/MenuContent.tsx
- src/layouts/components/SideNav.tsx
- src/router/index.ts
暂无相关issue
```json
{
path: '/module1',
component: Layout,
redirect: '/module1/list',
name: 'MODULE1',
meta: { title: '模块1', icon: ListIcon, single: true },
children: [
{
path: 'list',
name: 'MODULE1_LIST',
component: () => import('@/pages/module1/list/index.vue'),
meta: { title: '列表页' },
},
{
path: 'view',
name: 'MODULE1_VIEW',
component: () => import('@/pages/module1/view/index.vue'),
meta: { title: '详情页' },
},
{
path: 'edit',
name: 'MODULE1_EDIT',
component: () => import('@/pages/module1/edit/index.vue'),
meta: { title: '编辑页' },
},
],
}
```
当遇到以上的路由配置时，现有的实现方案就会出现：路由到【详情页或编辑页】时，父菜单没有加上选中态样式；
解决方案：
* 优化代码，将之前两处重复的代码逻辑迁移至路由模块，去除冗余代码
* 新增逻辑，如果当前选中的路由属于某一父菜单，则将该父菜单的value值设为当前路由，这样就能统一处理以上配置或之前分隔菜单带来的问题
- fix(Menu): 统一处理激活菜单样式问题
> 优化菜单选中判断逻辑

- src/layouts/index.tsx
- src/store/modules/tabs-router.ts
#166 
问题由【`login`页面不应该出现在多标签页】引发
- fix(多标签): 屏蔽不应该出现在多标签页的页面
> fix issue-166

- src/layouts/components/SideNav.tsx
1. 当前Starter演示项目中，在页面刷新后、通过URL直接访问等场景下，导航菜单不会按照当前激活的子菜单情况展开，使用上会比较迷惑。
2. 增加了一个通过当前激活菜单构造menu defaultExpanded的方法解决这个问题。
- feat(sidenav): 增加导航菜单在URL访问和刷新场景下的的默认展开
> feat(sidenav): add default expanded

- src/pages/list/base/index.vue
- src/pages/list/components/CommonTable.vue
- src/style/layout.less
自定义全局样式前缀的场景下，部分`js`中的样式选择器依旧是写死的`tdesign-starter`，`src/style/layout.less`中也有未随配置更改的样式`.tdesign-starter-link`
- fix(style): 部分选择器未随自定义样式前缀更改 ...
> fix(style): 部分选择器未随自定义样式前缀更改

- src/layouts/index.tsx
- src/store/modules/tabs-router.ts
- src/types/interface.d.ts
如某一路由带有重要参数时，切换其他标签重新切换回来后，参数丢失。
让tabs-router支持存储路由query，以保留页面参数，来回切换tab后不丢失路由参数。
- feat: Tabs新增存储路由的query参数
> feat: tabs-router 支持存储路由的query，保证切换tab时，能保留页面参数

- src/layouts/components/SideNav.vue
|修改前|修改后|
|  ----  | ----  |
|![image](https://user-images.githubusercontent.com/487040/188538227-12195c98-bb23-4193-8535-11ff7dc3f223.png)|![image](https://user-images.githubusercontent.com/487040/188538301-1d8f4e0a-6337-4f0c-a36e-5b7c36a3c3a2.png)|
fix(sidenav): 修复侧边栏折叠时版本号前显示 false 问题
> fix(sidenav): 修复侧边栏折叠时版本号前显示 false 问题

- src/pages/result/browser-incompatible/index.vue
`推荐浏览器` 卡片在响应式（变更浏览器高度）时，显示效果不好。
考虑到 `result` 样式问题，删除了 `返回首页` 按钮，既然浏览器不兼容，那么返回首页也一样不兼容。
|修改前|修改后|
|  ----  | ----  |
|![image](https://user-images.githubusercontent.com/487040/189090554-6f224b16-3b60-46d8-9086-bb9aea8023b0.png)|![image](https://user-images.githubusercontent.com/487040/189317032-b401a1dc-b24d-4961-ab7e-bae9e7e200fa.png)|
- fix: 修复浏览器不兼容页中浏览器推荐卡片遮挡页脚信息问题
> fix: 修复浏览器不兼容页中浏览器推荐卡片遮挡页脚信息问题

- src/utils/request/index.ts
Avoid changing Content-Type to be  text/plain when retrying request
- 
- fix: avoid changing Content-Type to be text/plain
> fix: avoid changing Content-Type to be text/plain

- src/layouts/components/LayoutContent.vue
- src/store/modules/tabs-router.ts
> feat: 多标签Tab页支持拖拽排序

- src/layouts/setting.vue
- src/store/modules/setting.ts
setting组件和setting store 有相同的逻辑代码，简化了一下。
> pref: 优化修改主题色的逻辑

- .gitattributes
- .vscode/settings.json
> perf: 规范不同系统中的结束符

- src/permission.ts
- src/store/modules/user.ts
- src/utils/request/index.ts
1. 底层携带`token`从`localStorage`中获取`token`，而`store`中并未对`localStorage`的`TOKEN_NAME`键进行赋值，`sotore`做了持久化，亦可修改下面的获取方式从`userStore`中获取
2. 另外，这里默认开启`withCredentials`则在跨域请求时对后端的安全性要求更高，强制要求`Access-Control-Allow-Origin`必须返回当前域，`axios`组件该参数默认貌似是关闭的，是否应该当开发者明确自己的需求必须携带cookie时主动打开该配置，而不是默认开启，因为大部分项目应该不需要携带cookie。
以上属于个人简单测试后的拙见，仅供参考
- fix: 修复 store 中并未对 localStorage 的 TOKEN_NAME 键进行赋值的缺陷
> fix: 修复 store 中并未对 localStorage 的 TOKEN_NAME 键进行赋值的缺陷

- src/store/modules/tabs-router.ts
(missing detect adppend multi tabs, refer e8509fd)
Closed #522 
按之前的设计，通过ignoreCacheRoutes实现禁用keepalive和多标签页（因为多标签依赖页面需要有保活能力，没有保活能力页面，不该进行多标签页的处理吧）。在https://github.com/Tencent/tdesign-vue-next-starter/pull/470变更后，没有对新增的meta.keepAlive判断是否将路由添加至多标签页。
增加判断meta.keepAlive !== false解决
- fix: 修复多标签页保活问题
> fix: 修复多标签页保活问题

- src/api/model/permissionModel.ts
- src/layouts/components/Breadcrumb.vue
- src/types/interface.d.ts
- src/utils/route/index.ts
fix https://github.com/Tencent/tdesign-vue-next-starter/issues/613
- fix(面包屑): 国际化
> fix: breadcrumb  i18n

- .gitignore
- package.json
- chore: 更新组件库版本
- chore: 更新ignore描述
> chore: update version

- src/locales/index.ts
- src/utils/route/index.ts
> chore: fix type

- src/App.vue
- src/layouts/components/Content.vue
- Vue3 修改了[过渡效果的类名](https://cn.vuejs.org/guide/built-ins/transition.html#named-transitions) `.fade-enter` -> `.fade-enter-from` 
- `transition` 组件未添加 `mode="out-in"`
- fix(starter): 修复路由切换时过渡动画异常的问题
> fix: 修复路由切换时过渡动画异常的问题

- src/config/style.ts
- src/layouts/components/Header.vue
- src/layouts/components/LayoutSideNav.vue
- src/layouts/components/SideNav.vue
- src/layouts/setting.vue
- src/locales/lang/en_US/layout.ts
- src/locales/lang/zh_CN/layout.ts
- src/store/modules/setting.ts
- src/style/layout.less
closed #447 
link #657
⚠️ **Breaking Change: 配置文件有新增和修改，该操作为BC操作，出现样式异常请尝试clear local storge**⚠️
- feat: 新增侧边栏颜色切换
- fix: 修复头部元素与Logo偏移的问题
- fix: 修复部分i18n未引用的问题
> feat: 新增侧边栏颜色切换

- src/pages/dashboard/base/components/MiddleChart.vue
- src/pages/dashboard/base/index.ts
link #555 
Dev模式下显示正常但在Preview模式下会出现环形图内标签文字重叠的问题。
而ECharts官方对此问题的建议是不要将标签设置在环形图内，包括官方示例列表中也没有该类示例
[相关Issue](https://github.com/apache/echarts/issues/18119)
⚠️ **请注意：** 因为如果开放用户自由选择会导致标签再次重叠，因此默认禁用，暂时无解⚠️
- fix: 修复ECharts环形图文字重叠的问题
> fix: 修复ECharts环形图文字重叠的问题

- src/permission.ts
当链接为/sale/custom/info?id=996这类带get参数退出再登录时，不能正确的带着参数进行跳转
应当将query合并进来，方可正常跳转
带get参数时能正常跳转
- feat(Router): 路由跳转携带参数
> feat(Router): 路由跳转携带参数

- src/config/style.ts
- src/layouts/components/SideNav.vue
- src/layouts/setting.vue
- src/locales/lang/en_US/layout.ts
- src/locales/lang/zh_CN/layout.ts
- src/router/index.ts
> feat: 新增菜单自动折叠

- src/components/color/index.vue
- src/components/result/index.vue
- src/components/thumbnail/index.vue
- src/components/trend/index.vue
- src/layouts/components/Header.vue
- src/layouts/components/MenuContent.vue
- src/layouts/components/SideNav.vue
- src/pages/list/card/components/DialogForm.vue
- https://github.com/Tencent/tdesign-vue-next-starter/issues/750#issue-2506083613
- refactor: defineProps改为Vue3.5解构语法
> refactor: defineProps改为Vue3.5解构语法

- PUBLISH.md
- package.json
> chore: update dep version

- package-lock.json
- package.json
- src/pages/list/base/index.vue
- chore(deps): 升级组件库版本
- fix(types): 修复@select-change事件类型
> fix(types): 修复@select-change事件类型

- src/utils/route/index.ts
- close https://github.com/Tencent/tdesign-vue-next-starter/issues/824
> chore: reduce production request by default
